---
- name: Playbook to reboot host
  hosts: "{{ target }}"
  gather_facts: no

  tasks:
    - name: Debug
      debug:
        msg: "Will reboot an host"

    - name: rebooting
      reboot:
        reboot_timeout: 300
      become: true
      become_user: root
