---
- name: POST-PATCH MANAGEMENT | Post play
  hosts: localhost
  gather_facts: false
  user: ansible
  tasks:
    - name: "CHECK | Target must not have more than 221 characters"
      assert:
        that: target |length <= 221
        fail_msg: The target have more than 221 characters, it will result in more than 255 filename characters which is over filesystem limits. Customs tasks "after everything" could not be loaded. Check the Rundeck job inventory parameter and fix it if needed.
        # quiet: true #Only supported in Ansible >= 2.8
      ignore_errors: true
      register: check_length

    - name: "CHECK | Does after_everything_{{ target }}_custom_tasks.yml file exist ?"
      stat:
        path: "{{ playbook_dir }}/patchmanagement/after_everything_{{ target }}_custom_tasks.yml"
      register: custom_after_everything
      when:
        - not check_length.failed
        - client is defined and client != ""

    - name: "INCLUDE | after_everything_{{ target }}_custom_tasks.yml exists"
      include_tasks: "{{ custom_after_everything.stat.path }}"
      when:
        - custom_after_everything is defined
        - custom_after_everything.stat.exists |default(false)
